# http service configuration.
http:
  address: 0.0.0.0:8080

  workers:
    command: "php app.php"

# queue and jobs
jobs:
  dispatch:
    app-job-*.pipeline: "local"
    app-application-command-*.pipeline: "local"

  pipelines:
    local:
      broker: "ephemeral"
#    remote:
#      broker: amqp
#      queue:  messages_for_spiral
#      maxAttempts: 2
#      exchange: amqp.topic

  consume: ["local"]

  workers:
    command: "php app.php"
    pool.numWorkers: 2

#  amqp.addr: amqp://user:user@rabbitmq:5672/

# serve static files
static:
  dir:    "public"
  forbid: [".php", ".htaccess"]

metrics:
  # prometheus client address (path /metrics added automatically)
  address: 0.0.0.0:2112
rpc:
#  enable: true
#  listen: tcp://application:6001
  #FIXME - see: vendor/spiral/framework/src/Bootloader/ServerBootloader.php -> private const RPC_DEFAULT

# control the max memory usage
limit:
  services:
    http.maxMemory: 100
    jobs.maxMemory: 100