version: "3.8"
services:
    application:
        image: spiral-application:latest
        container_name: spiral-application
        build:
            context: base/application
        restart: always
        volumes:
            - ../:/application
            - ./config/application/.bashrc:/home/developer/.bashrc
            - ./config/application/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        working_dir: /application
        command: ['tail', '-f', '/dev/null']
        ports:
        - 8080:8080
        - 2112:2112
        networks:
            spiral:
                aliases:
                    - application

networks:
    spiral:
