version: "3.7"
services:

    spiral-application:
        image: spiral-application:latest
        build:
            context: base
            dockerfile: application/Dockerfile
            args:
                DEVELOPER_UID: ${DEVELOPER_UID}
        container_name: spiral-application
        restart: always
        ports: [8080:8080]
        volumes:
            - ..:/application
            - ./dev/config/spiral-application/.bashrc:/home/developer/.bashrc
            - ./dev/config/spiral-application/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        working_dir: /application
        command: ['tail', '-f', '/dev/null']
        networks:
            spiral:
                aliases:
                    - application
        hostname: spiral-application
networks:
    spiral: